language: node_js
sudo: false
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ZXF8/E8iXA3nc4z2JCUJVl4GUhN2RcvLgozx+NO6C34PPDV3X2R1aVCbm7JJRRsI0/qov2BaOMaUHCx90d7U+bVyqkfgXLHkz8Kd0vWwh9HO96WD124bzeAi5a/a7hK15M8iAwUeZctB1qZwQErAfy4WSEv/MoYWmqp9oOO4ug0=
  file:
    - 'afinn-96.js'
    - 'afinn-96.min.js'
  on:
    tags: true
