language: node_js
sudo: false
node_js:
- '4.0'
- '9.0'
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: ZIRIvMbRhYBceujQMt6GUtUD+cvIrbOlx/NKUCaByDjPMKQJeYqh6An79OQvfWt8Wauba5yLbTqSKzCe94zcxTfsXFzg8jBQIuHH8kuGMQJeFWyn/qZYrfxySnDfjOEXmrDQ6/CpCRX/xnJMBmy49H9FXmo9enBVBqqrSFA3Ijs=
    on:
      tags: true
      node: '9.0'
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: ecLbntfUMYhGv0V7uyv0BIIt6s2x05/dXC1B8x7+qQw7/edh065/LekjNz+G0sy3yXH8Ud+4RM6gl4vqPrAlPXWClqUPAo9KwuWsZe2TqIZwrXwTTdE/vgwa3G6A5iuP+pmS6PLzdwWcM3osdSJHkJSxzkdxasbeYYzWLAIuF+0=
    file:
      - "afinn-96.js"
      - "afinn-96.min.js"
    on:
      tags: true
      node: '9.0'
